# Generated by Django 2.2.6 on 2019-11-08 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('name', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(choices=[('done', 'Done'), ('in_process', 'In process')], default='in_process', max_length=20)),
                ('card_number', models.BigIntegerField(help_text='Such as 1234-5678-1234-5678', null=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Wrong card number')])),
                ('card_cvs', models.IntegerField(help_text='Such as 913', validators=[django.core.validators.RegexValidator('^\\d{3}$')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
